package SimRATApp;

/**
* SimRATApp/ImageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimRAT.idl
* Sunday, June 8, 2014 1:31:33 AM IST
*/

public final class ImageHolder implements org.omg.CORBA.portable.Streamable
{
  public SimRATApp.Image value = null;

  public ImageHolder ()
  {
  }

  public ImageHolder (SimRATApp.Image initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SimRATApp.ImageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SimRATApp.ImageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SimRATApp.ImageHelper.type ();
  }

}
