package SimRATApp;

/**
 * SimRATApp/Image.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from SimRAT.idl Sunday, June 8, 2014 1:31:33 AM IST
 */
public final class Image implements org.omg.CORBA.portable.IDLEntity {

    public byte img[] = null;

    public Image() {
    } // ctor

    public Image(byte[] _img) {
        img = _img;
    } // ctor
} // class Image
