package SimRATApp;

/**
* SimRATApp/SimRATFileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimRAT.idl
* Sunday, June 8, 2014 1:31:33 AM IST
*/

public final class SimRATFileHolder implements org.omg.CORBA.portable.Streamable
{
  public SimRATApp.SimRATFile value = null;

  public SimRATFileHolder ()
  {
  }

  public SimRATFileHolder (SimRATApp.SimRATFile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SimRATApp.SimRATFileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SimRATApp.SimRATFileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SimRATApp.SimRATFileHelper.type ();
  }

}
