package SimRATApp;


/**
* SimRATApp/SimRATFile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimRAT.idl
* Sunday, June 8, 2014 1:31:33 AM IST
*/

public final class SimRATFile implements org.omg.CORBA.portable.IDLEntity
{
  public String fileName = null;
  public byte file[] = null;

  public SimRATFile ()
  {
  } // ctor

  public SimRATFile (String _fileName, byte[] _file)
  {
    fileName = _fileName;
    file = _file;
  } // ctor

} // class SimRATFile
