package SimRATApp;

/**
* SimRATApp/SimRATHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SimRAT.idl
* Sunday, June 8, 2014 1:31:33 AM IST
*/

public final class SimRATHolder implements org.omg.CORBA.portable.Streamable
{
  public SimRATApp.SimRAT value = null;

  public SimRATHolder ()
  {
  }

  public SimRATHolder (SimRATApp.SimRAT initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SimRATApp.SimRATHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SimRATApp.SimRATHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SimRATApp.SimRATHelper.type ();
  }

}
